import Head from 'next/head';
import Layout from '@/components/Layout';
import Image from 'next/image';
import profilePicture from '@/public/images/profile/developer-pic-1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from '@/public/images/svgs/miscellaneous_icons_1.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light ">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex lg:flex-col items-center justify-between w-full">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePicture}
                alt="Picture of the author"
                className="w-full h-auto lg:hidden  md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,(max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-1/2 lg:w-full flex flex-col items-center self-center lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                - As askilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href={'/dummy.pdf'}
                  target={'_blank'}
                  className="flex items-center bg-dark text-light text-lg font-semibold p-2.5 px-6 rounded-lg
                  hover:bg-light hover:text-dark transition duration-300 ease-in-out
                  border-2 border-solid border-transparent hover:border-dark
                  dark:bg-light dark:text-dark 
                  hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                  md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link
                  href={'mailto: simonetvia@outlook.com'}
                  target={'_blank'}
                  className="ml-4 text-lg text-dark underline capitalize font-medium
                  hover:text-slate-500 transition duration-300 ease-in-out dark:text-light md:text-base "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 w-24 md:hidden ">
          <Image
            src={lightBulb}
            alt="Picture of the author"
            className="w-full h-auto"
          />
        </div>
      </main>
    </>
  );
}
